### ISSUE TITLE
A Not Working Link

### ISSUE THREAD

**Issue by 1nfinityLoop** [zhengthomastang/2018AICity_TeamUW#15]
hello guys , i look forward to take a look at your trained model code ( of the CVPR 2018 AI city challenge ) , but unfortunately the link that's in your github https://drive.google.com/open?id=1k1ha7q_Zuv3V9VL_8k47vCaLB0tS8w-J is not working anymore , i would be so grateful if you'll provide me with another link to access the trained model (weights) , for educational purpose , please.
Cordially

**Comment by zhengthomastang** [comment]
Thank you for letting us know. We have updated the all the links in the README files. They should be ready to download now.
