### ISSUE TITLE
Height of vehicles effect on real distance between 2 frames

### ISSUE THREAD

**Issue by navidnadery** [zhengthomastang/2018AICity_TeamUW#31]
Hi, Thank you for the tutorial.
I have a problem in estimating real distance of 2 objects (an object in 2 consecutive frames). Height of the vehicle (from ground) can influence on our estimate, how can I handle it?
In step 2, you use camera calibration then perspective, however they assume that all object are on ground and are flat.

I really appreciate your guidance

**Comment by zhengthomastang** [comment]
That depends on how you decide the foot points of the two objects. The method we used based on bounding boxes may not work well for high precision. I would suggest to choose the center of mass of the segmented mask. But the most accurate approach might be training an additional model to estimate the foot points of vehicles.

**Comment by navidnadery** [comment]
Thank you for your recommendations. I've tried centering of mass, but it does not help. However, training a model seems good.
