### ISSUE TITLE
Some questions about 2_CAM_CAL

### ISSUE THREAD

**Issue by Luna2199** [zhengthomastang/2018AICity_TeamUW#34]
I'm sorry if it bothers you。When I started working on camera calibration(2_CAM_CAL), I ran into a problem.

- in the window of “**selector of vanishing lines**”. Please select a pair of vanishing lines first and then another pair, like this pic.
   
![微信截图_20220630120733](https://user-images.githubusercontent.com/21285692/176591774-af995976-f3b5-4093-aae8-cdb7ebf431b9.png)
**The I got the calVr and calVl**： `Vanishing point (right): (1093,38)
Vanishing point (left): (-13993,10)
`

- But the **3dgrid.jpg** that I got  is not performing very well, where am I going wrong and how can I improve it.
![3dgrid](https://user-images.githubusercontent.com/21285692/176592518-a905a82e-c683-4231-b5db-7fab2f5cdb50.jpg)

Thanks

**Comment by zhengthomastang** [comment]
This may happen occasionally because the two horizontal pairs are too parallel with each other, causing the vanishing point lying at infinity. Please try selecting different pairs of vanishing lines until the results converge properly.
